version: '3.4'

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/db/imdble.db
    ports:
      - 3000:3000
    volumes:
      - ~/.config/imdble/:/db/
